os: Visual Studio 2015

version: 1.0.2.{build}

configuration:
- Release

platform:
- Any CPU
- x64
- x86

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

install:
- ps: Start-FileDownload 'https://download.microsoft.com/download/0/A/3/0A372822-205D-4A86-BFA7-084D2CBE9EDF/DotNetCore.1.0.1-SDK.1.0.0.Preview2-003133-x64.exe'
- cmd: DotNetCore.1.0.1-SDK.1.0.0.Preview2-003133-x64.exe /quiet

environment:
  PATH: $(PATH);$(PROGRAMFILES)\dotnet\

build_script:
- appveyor-retry dotnet restore .\src\MediaInfo.DotNetWrapper
- dotnet build .\src\MediaInfo.DotNetWrapper\project.json -c %CONFIGURATION%
- dotnet pack -c Release --no-build --version-suffix %LABEL% -o .\artifacts .\src\MediaInfo.DotNetWrapper\project.json

artifacts:
- path: artifacts\**\*.*

cache:
- '%USERPROFILE%\.nuget\packages'